import Link from 'next/link';
import type { ComplianceReport } from '@/lib/safety/compliance';

/**
 * Compliance Health Card — sits at the top of the Safety home page.
 *
 * Left: big score / grade / tone-coloured headline.
 * Right: per-factor breakdown so the chef sees exactly which corner is
 * dragging things down, each row linked into the surface where they
 * can act on it.
 *
 * The per-factor `message` is generated by detectors in
 * `src/lib/safety/compliance.ts` — the same forward-thinking pattern
 * the Looking Ahead bar uses, so the card and the bar stay coherent.
 */
export function ComplianceCard({ report }: { report: ComplianceReport }) {
  const accent =
    report.tone === 'healthy'
      ? 'border-l-healthy'
      : report.tone === 'attention'
        ? 'border-l-attention'
        : 'border-l-urgent';

  const grade = report.grade;
  const gradeTone =
    grade === 'A'
      ? 'text-healthy'
      : grade === 'B'
        ? 'text-ink'
        : grade === 'C'
          ? 'text-attention'
          : 'text-urgent';

  return (
    <div
      className={
        'bg-card border border-rule border-l-[3px] ' +
        accent +
        ' mb-6 grid grid-cols-1 lg:grid-cols-[280px_1fr]'
      }
    >
      <div className="px-7 py-6 border-b lg:border-b-0 lg:border-r border-rule">
        <div className="font-display font-semibold text-[10px] tracking-[0.3em] uppercase text-gold mb-2.5">
          Compliance · Today
        </div>
        <div className="flex items-baseline gap-3 mb-1">
          <span className="font-mono font-medium text-[56px] text-ink leading-none">
            {report.score}
          </span>
          <span
            className={
              'font-display font-bold text-[28px] leading-none ' + gradeTone
            }
          >
            {grade}
          </span>
        </div>
        <div className="font-sans text-xs text-muted-soft mb-3 tracking-wide uppercase">
          /100
        </div>
        <p
          className="font-serif italic text-[15px] text-ink-soft leading-snug"
          dangerouslySetInnerHTML={{ __html: report.headline }}
        />
      </div>

      <div className="px-7 py-6">
        <div className="font-display font-semibold text-[10px] tracking-[0.3em] uppercase text-muted mb-3">
          Where it&apos;s landing
        </div>
        <div className="space-y-3">
          {report.factors
            .slice()
            .sort((a, b) => a.score - b.score)
            .map((f) => (
              <Link
                key={f.key}
                href={f.href}
                className="block group no-underline text-inherit"
              >
                <div className="flex items-baseline gap-3 mb-1">
                  <span
                    className={
                      'font-display font-semibold text-[10px] tracking-[0.18em] uppercase ' +
                      (f.state === 'urgent'
                        ? 'text-urgent'
                        : f.state === 'attention'
                          ? 'text-attention'
                          : 'text-healthy')
                    }
                  >
                    {f.label}
                  </span>
                  <span className="font-mono text-xs text-ink-soft">{f.score}/100</span>
                  <span className="font-sans text-[10px] text-muted-soft ml-auto">
                    weight {Math.round(f.weight * 100)}%
                  </span>
                </div>
                <div className="w-full h-1.5 bg-rule rounded-sm overflow-hidden mb-1.5">
                  <div
                    className={
                      'h-full transition-all ' +
                      (f.state === 'urgent'
                        ? 'bg-urgent'
                        : f.state === 'attention'
                          ? 'bg-attention'
                          : 'bg-healthy')
                    }
                    style={{ width: f.score + '%' }}
                  />
                </div>
                <p
                  className="font-serif text-[13px] text-ink-soft leading-snug group-hover:text-ink transition-colors"
                  dangerouslySetInnerHTML={{ __html: f.message }}
                />
              </Link>
            ))}
        </div>
      </div>
    </div>
  );
}
