import { Document, Page, Text, View } from '@react-pdf/renderer';
import { pdfStyles, s } from './styles';
import {
  CORRECTIVE_ACTION_LIBRARY,
  HACCP_STATUS_LABEL,
  MONITOR_SOURCE_LABEL,
  REVIEW_CADENCE_LABEL,
  type HaccpBody,
  type HaccpCcp,
  type HaccpFlowStep,
  type HaccpHazard,
  type HaccpHazardKind,
  type HaccpMonitorSource,
  type HaccpPlan,
  type HaccpReviewCadence,
} from '@/lib/safety/haccp';

const HAZARD_KIND: Record<HaccpHazardKind, string> = {
  biological: 'Biological',
  chemical: 'Chemical',
  physical: 'Physical',
  allergen: 'Allergen',
};

const dateFmt = new Intl.DateTimeFormat('en-GB', {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
});

function fmtDate(s: string | null | undefined): string {
  if (!s) return '—';
  const d = new Date(s);
  if (Number.isNaN(d.getTime())) return s;
  return dateFmt.format(d);
}

export function HaccpPlanDoc({
  plan,
  siteName,
}: {
  plan: HaccpPlan;
  siteName: string;
}) {
  const body: HaccpBody = plan.body ?? {};
  const step1 = body.step_1 ?? {};
  const step2 = body.step_2 ?? {};
  const step3 = body.step_3 ?? {};
  const step4 = body.step_4 ?? {};
  const step5 = body.step_5 ?? {};
  const step6 = body.step_6 ?? {};
  const step7 = body.step_7 ?? {};
  const step9 = body.step_9 ?? {};

  const tradingName =
    (step1.trading_name as string | undefined) ?? siteName ?? '—';
  const generatedAt = new Date();

  const ccps = (step3.ccps ?? []) as HaccpCcp[];
  const hazards = (step2.hazards ?? []) as HaccpHazard[];
  const flow = (step2.flow_steps ?? []) as HaccpFlowStep[];
  const limits = (step4.critical_limits ?? []) as Array<{
    ccp_id: string;
    parameter: string;
    operator: string;
    min_value: string;
    max_value: string;
    unit: string;
    reference: string;
  }>;
  const monitoring = (step5.monitoring ?? []) as Array<{
    ccp_id: string;
    source: HaccpMonitorSource;
    what: string;
    who: string;
    how: string;
    frequency: string;
  }>;
  const correctives = (step6.corrective_actions ?? []) as Array<{
    ccp_id: string;
    template_ids: string[];
    custom_md: string;
    who_decides: string;
  }>;
  const verification = step7.verification as
    | {
        cadence?: HaccpReviewCadence;
        who?: string;
        last_review?: string | null;
        next_review?: string | null;
        notes_md?: string;
      }
    | undefined;

  function ccpName(id: string): string {
    return ccps.find((c) => c.id === id)?.name || 'Unnamed CCP';
  }

  return (
    <Document title={`${tradingName} — HACCP plan`} author="Palatable">
      <Page size="A4" style={pdfStyles.page}>
        <View style={pdfStyles.headerBar} fixed>
          <View style={{ flexDirection: 'row' }}>
            <Text style={pdfStyles.brandWord}>PALATABLE</Text>
            <Text style={pdfStyles.brandDot}> ·</Text>
          </View>
          <Text style={pdfStyles.docMeta}>
            HACCP PLAN · {fmtDate(generatedAt.toISOString())}
          </Text>
        </View>

        <Text style={pdfStyles.title}>
          <Text>{tradingName} — </Text>
          <Text style={pdfStyles.titleEm}>HACCP plan.</Text>
        </Text>
        <Text style={pdfStyles.subtitle}>
          A documented food safety management system based on HACCP
          principles. Generated by Palatable from the operator&apos;s data,
          reviewed and confirmed by the named Food Business Operator.
        </Text>

        <View style={s(pdfStyles.kvRow)}>
          <Text style={pdfStyles.kvKey}>STATUS</Text>
          <Text style={pdfStyles.kvVal}>
            {HACCP_STATUS_LABEL[plan.status]}
            {plan.signed_off_at
              ? ` · signed off ${fmtDate(plan.signed_off_at)}`
              : ''}
          </Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>GENERATED</Text>
          <Text style={pdfStyles.kvVal}>{fmtDate(generatedAt.toISOString())}</Text>
        </View>

        <Text style={pdfStyles.sectionLabel}>STEP 1</Text>
        <Text style={pdfStyles.sectionTitle}>Business profile.</Text>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>TRADING NAME</Text>
          <Text style={pdfStyles.kvVal}>{tradingName}</Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>LEGAL ENTITY</Text>
          <Text style={pdfStyles.kvVal}>
            {(step1.legal_entity as string | undefined) || '—'}
          </Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>FSA REG</Text>
          <Text style={pdfStyles.kvVal}>
            {step1.fsa_registration || '—'}
          </Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>KITCHEN TYPE</Text>
          <Text style={pdfStyles.kvVal}>
            {(step1.kitchen_type as string | undefined) || '—'}
          </Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>TEAM SIZE</Text>
          <Text style={pdfStyles.kvVal}>
            {(step1 as { team_size_band?: string }).team_size_band ??
              String(step1.team_size ?? '—')}
          </Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>SERVICES</Text>
          <Text style={pdfStyles.kvVal}>
            {(step1.services ?? []).join(', ') || '—'}
          </Text>
        </View>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>FBO</Text>
          <Text style={pdfStyles.kvVal}>
            {(step1 as { person_responsible?: string }).person_responsible ||
              '—'}
          </Text>
        </View>
        {step1.notes_md && (
          <View style={{ marginTop: 6 }}>
            <Text style={pdfStyles.bodySoft}>{step1.notes_md}</Text>
          </View>
        )}

        <Text style={pdfStyles.sectionLabel}>STEP 2</Text>
        <Text style={pdfStyles.sectionTitle}>Menu &amp; hazard analysis.</Text>
        <Text style={pdfStyles.body}>
          <Text style={pdfStyles.bold}>Flow of food through the kitchen.</Text>
        </Text>
        {flow.length === 0 ? (
          <Text style={pdfStyles.bodySoft}>(No flow steps captured.)</Text>
        ) : (
          flow.map((f) => (
            <View key={f.id} style={pdfStyles.kvRow}>
              <Text style={pdfStyles.kvKey}>
                {f.name.toUpperCase().slice(0, 12)}
              </Text>
              <Text style={pdfStyles.kvVal}>{f.description || '—'}</Text>
            </View>
          ))
        )}

        <Text style={s(pdfStyles.body, { marginTop: 12 })}>
          <Text style={pdfStyles.bold}>Hazards identified.</Text>
        </Text>
        {hazards.length === 0 ? (
          <Text style={pdfStyles.bodySoft}>(No hazards captured.)</Text>
        ) : (
          hazards.map((h) => (
            <View key={h.id} style={pdfStyles.card}>
              <Text style={pdfStyles.cardTitle}>
                {HAZARD_KIND[h.kind]} — {h.description || '—'}
              </Text>
              {h.source && (
                <Text style={pdfStyles.metaLine}>Source: {h.source}</Text>
              )}
            </View>
          ))
        )}

        <Text style={pdfStyles.sectionLabel}>STEPS 3-6</Text>
        <Text style={pdfStyles.sectionTitle}>
          Critical Control Points, limits, monitoring, corrective actions.
        </Text>
        {ccps.length === 0 ? (
          <Text style={pdfStyles.bodySoft}>(No CCPs defined.)</Text>
        ) : (
          ccps.map((c) => {
            const limit = limits.find((l) => l.ccp_id === c.id);
            const mon = monitoring.find((m) => m.ccp_id === c.id);
            const corr = correctives.find((x) => x.ccp_id === c.id);
            const corrTemplates = (corr?.template_ids ?? [])
              .map((tid) => CORRECTIVE_ACTION_LIBRARY.find((t) => t.id === tid))
              .filter(Boolean);
            const linkedHazard = hazards.find((h) => h.id === c.hazard_ref);
            return (
              <View key={c.id} style={pdfStyles.card} wrap={false}>
                <Text style={pdfStyles.cardTitle}>
                  CCP — {c.name || 'Unnamed CCP'}
                </Text>
                {linkedHazard && (
                  <Text style={pdfStyles.metaLine}>
                    Hazard: {HAZARD_KIND[linkedHazard.kind]} —{' '}
                    {linkedHazard.description}
                  </Text>
                )}
                <View style={pdfStyles.rowDivider} />
                <View style={pdfStyles.kvRow}>
                  <Text style={pdfStyles.kvKey}>CRITICAL LIMIT</Text>
                  <Text style={pdfStyles.kvVal}>
                    {c.critical_limit || '—'}
                    {limit && (
                      <Text>
                        {`  (${limit.operator} ${
                          limit.min_value || limit.max_value
                        }${limit.unit ? ' ' + limit.unit : ''})`}
                      </Text>
                    )}
                  </Text>
                </View>
                {c.justification && (
                  <View style={pdfStyles.kvRow}>
                    <Text style={pdfStyles.kvKey}>JUSTIFICATION</Text>
                    <Text style={pdfStyles.kvVal}>{c.justification}</Text>
                  </View>
                )}
                {limit?.reference && (
                  <View style={pdfStyles.kvRow}>
                    <Text style={pdfStyles.kvKey}>REFERENCE</Text>
                    <Text style={pdfStyles.kvVal}>{limit.reference}</Text>
                  </View>
                )}
                <View style={pdfStyles.rowDivider} />
                <Text style={pdfStyles.metaLine}>MONITORING</Text>
                {mon ? (
                  <>
                    <View style={pdfStyles.kvRow}>
                      <Text style={pdfStyles.kvKey}>WHAT</Text>
                      <Text style={pdfStyles.kvVal}>{mon.what || '—'}</Text>
                    </View>
                    <View style={pdfStyles.kvRow}>
                      <Text style={pdfStyles.kvKey}>WHO</Text>
                      <Text style={pdfStyles.kvVal}>{mon.who || '—'}</Text>
                    </View>
                    <View style={pdfStyles.kvRow}>
                      <Text style={pdfStyles.kvKey}>HOW</Text>
                      <Text style={pdfStyles.kvVal}>{mon.how || '—'}</Text>
                    </View>
                    <View style={pdfStyles.kvRow}>
                      <Text style={pdfStyles.kvKey}>FREQUENCY</Text>
                      <Text style={pdfStyles.kvVal}>{mon.frequency || '—'}</Text>
                    </View>
                    <View style={pdfStyles.kvRow}>
                      <Text style={pdfStyles.kvKey}>RECORDED IN</Text>
                      <Text style={pdfStyles.kvVal}>
                        {MONITOR_SOURCE_LABEL[mon.source] || mon.source}
                      </Text>
                    </View>
                  </>
                ) : (
                  <Text style={pdfStyles.bodySoft}>(Not yet defined.)</Text>
                )}
                <View style={pdfStyles.rowDivider} />
                <Text style={pdfStyles.metaLine}>CORRECTIVE ACTIONS</Text>
                {corrTemplates.length === 0 && !corr?.custom_md ? (
                  <Text style={pdfStyles.bodySoft}>(Not yet defined.)</Text>
                ) : (
                  <>
                    {corrTemplates.map((t) =>
                      t ? (
                        <View key={t.id} style={pdfStyles.kvRow}>
                          <Text style={pdfStyles.kvKey}>•</Text>
                          <Text style={pdfStyles.kvVal}>
                            <Text style={pdfStyles.bold}>{t.label}.</Text>{' '}
                            {t.body}
                          </Text>
                        </View>
                      ) : null,
                    )}
                    {corr?.custom_md && (
                      <View style={pdfStyles.kvRow}>
                        <Text style={pdfStyles.kvKey}>•</Text>
                        <Text style={pdfStyles.kvVal}>
                          <Text style={pdfStyles.bold}>Custom action.</Text>{' '}
                          {corr.custom_md}
                        </Text>
                      </View>
                    )}
                    {corr?.who_decides && (
                      <View style={pdfStyles.kvRow}>
                        <Text style={pdfStyles.kvKey}>WHO DECIDES</Text>
                        <Text style={pdfStyles.kvVal}>{corr.who_decides}</Text>
                      </View>
                    )}
                  </>
                )}
                {c.recipe_ids && c.recipe_ids.length > 0 && (
                  <>
                    <View style={pdfStyles.rowDivider} />
                    <Text style={pdfStyles.metaLine}>
                      LINKED DISHES — {c.recipe_ids.length}
                    </Text>
                  </>
                )}
              </View>
            );
          })
        )}

        <Text style={pdfStyles.sectionLabel}>STEP 7</Text>
        <Text style={pdfStyles.sectionTitle}>Verification &amp; review.</Text>
        {verification ? (
          <>
            <View style={pdfStyles.kvRow}>
              <Text style={pdfStyles.kvKey}>CADENCE</Text>
              <Text style={pdfStyles.kvVal}>
                {verification.cadence
                  ? REVIEW_CADENCE_LABEL[verification.cadence]
                  : '—'}
              </Text>
            </View>
            <View style={pdfStyles.kvRow}>
              <Text style={pdfStyles.kvKey}>WHO REVIEWS</Text>
              <Text style={pdfStyles.kvVal}>{verification.who || '—'}</Text>
            </View>
            <View style={pdfStyles.kvRow}>
              <Text style={pdfStyles.kvKey}>LAST REVIEW</Text>
              <Text style={pdfStyles.kvVal}>
                {fmtDate(verification.last_review)}
              </Text>
            </View>
            <View style={pdfStyles.kvRow}>
              <Text style={pdfStyles.kvKey}>NEXT REVIEW</Text>
              <Text style={pdfStyles.kvVal}>
                {fmtDate(verification.next_review)}
              </Text>
            </View>
            {verification.notes_md && (
              <Text style={pdfStyles.bodySoft}>{verification.notes_md}</Text>
            )}
          </>
        ) : (
          <Text style={pdfStyles.bodySoft}>(Not yet defined.)</Text>
        )}

        <Text style={pdfStyles.sectionLabel}>STEP 9</Text>
        <Text style={pdfStyles.sectionTitle}>Annual review.</Text>
        <View style={pdfStyles.kvRow}>
          <Text style={pdfStyles.kvKey}>NEXT REVIEW</Text>
          <Text style={pdfStyles.kvVal}>
            {fmtDate((step9 as { next_review_date?: string }).next_review_date)}
          </Text>
        </View>
        {(step9 as { notes_md?: string }).notes_md && (
          <Text style={pdfStyles.bodySoft}>
            {(step9 as { notes_md?: string }).notes_md}
          </Text>
        )}

        <View style={pdfStyles.liability}>
          <Text style={pdfStyles.liabilityLabel}>
            STRONGER NOTICE — HACCP &amp; LEGAL DOCUMENTS
          </Text>
          <Text style={pdfStyles.liabilityBody}>
            Palatable generates a draft HACCP plan from your data. This wizard
            does not replace professional food safety advice. We strongly
            recommend the generated plan is reviewed by a qualified food
            safety adviser, your local authority Environmental Health team, or
            an accredited consultant before relying on it. Palatable is not a
            certification body, does not provide legal advice, and accepts no
            liability for the operation of your food business. The Food
            Business Operator named above remains fully accountable for
            compliance with UK food safety law.
          </Text>
        </View>

        <View style={pdfStyles.footerStrip} fixed>
          <Text style={pdfStyles.footerLeft}>
            {tradingName.toUpperCase()} · HACCP PLAN
          </Text>
          <Text
            style={pdfStyles.footerRight}
            render={({ pageNumber, totalPages }) =>
              `PAGE ${pageNumber} / ${totalPages}`
            }
          />
        </View>
      </Page>
    </Document>
  );
}
